version: "3"

x-app: &base-app
  build:
    context: .
  volumes:
    - ".:/app"

services:
  app:
    <<: *base-app
    command: "python3 manage.py runserver 0:8000"
    ports:
      - 8000:8000
  tailwind:
    <<: *base-app
    command: "python3 manage.py tailwind start"
    tty: true
